mm: Disable optimization for function shrink_page_list()
GCC version 5.4.1+svn241155-1 in Debian Stretch has a bug that breaks
the build. The error is attached.
TODO: Gigure out the actual bug or revert patch if a newer GCC is
available in Stretch.

/home/wolfi/6.0-romsrc/kernel/samsung/smdk4412/mm/vmscan.c: In function 'shrink_page_list':
/home/wolfi/6.0-romsrc/kernel/samsung/smdk4412/mm/vmscan.c:1019:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 1111 1814 1112 116 (parallel [
            (set (reg/v:SI 3 r3 [orig:111 nr_dirty ] [111])
                (and:SI (ne:SI (reg/v:SI 3 r3 [orig:111 nr_dirty ] [111])
                        (const_int 0 [0]))
                    (eq:SI (reg/v:SI 3 r3 [orig:111 nr_dirty ] [111])
                        (reg/v:SI 2 r2 [orig:112 nr_congested ] [112]))))
            (clobber (reg:CC 100 cc))
        ]) /home/wolfi/6.0-romsrc/kernel/samsung/smdk4412/mm/vmscan.c:1011 256 {*and_scc_scc_nodom}
     (nil))
/home/wolfi/6.0-romsrc/kernel/samsung/smdk4412/mm/vmscan.c:1019:1: internal compiler error: in extract_constrain_insn, at recog.c:2246

/home/wolfi/6.0-romsrc/kernel/samsung/smdk4412/mm/vmscan.c:1019:1: internal compiler error: Segmentation fault
arm-none-eabi-gcc: internal compiler error: Segmentation fault (program cc1)

Signed-off-by: Wolfgang Wiedmeyer <wolfgit@wiedmeyer.de>